spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost/car_price_pro?useSSL=false&allowPublicKeyRetrieval=true
    username: caruser
    password: carpass
#    url: jdbc: mysql://db_container/daily_report_system?useSSL=false&allowPublicKeyRetrieval=true
#    username: repuser
#    password: reppass
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
  mail:
    host: smtp.gmail.com
    port: 587
    username: udonishito0506@gmail.com
    password: byky ohgn svie rxrl
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 888492838675-4hj3hsssia5ako2lndop4jpav37prg5k.apps.googleusercontent.com
            client-secret: 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
