server:
  port: ${PORT:8080}  # Renderで必要（自動割当ポートに対応）

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  web:
    resources:
      static-locations: classpath:/static/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#spring:
#  jpa:
#    show-sql: true
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:mysql://localhost/car_price_pro_simple?useSSL=false&allowPublicKeyRetrieval=true
#    username: caruser
#    password: carpass
##    url: jdbc: mysql://db_container/daily_report_system?useSSL=false&allowPublicKeyRetrieval=true
##    username: repuser
##    password: reppass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always
#      encoding: UTF-8
#      
#  web:
#    resources:
#      static-locations: classpath:/static/, file:/Users/ryotaishito/CPCA/
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: udonishito0506@gmail.com
#    password: byky ohgn svie rxrl
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls.enable: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 888492838675-4hj3hsssia5ako2lndop4jpav37prg5k.apps.googleusercontent.com
#            client-secret: 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
#          line:
#            provider: line
#            client-id: 2007249399
#            client-secret: 1b8e662b3a7986321acf6019a2b05ca2
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: profile
#            client-name: LINE
#        provider:
#          line:
#            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
#            token-uri: https://api.line.me/oauth2/v2.1/token
#            user-info-uri: https://api.line.me/v2/profile
#            user-info-authentication-method: query
#            user-name-attribute: userId
#            jwk-set-uri: https://api.line.me/oauth2/v2.1/certs
              
